# Generated by Django 2.2.13 on 2022-05-21 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimientos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=40)),
                ('departamento', models.CharField(max_length=40)),
                ('precio_min', models.CharField(max_length=10)),
                ('precio_max', models.CharField(max_length=50)),
                ('parqueadero', models.BooleanField()),
                ('correo', models.EmailField(max_length=254)),
                ('tarjeta_credito', models.BooleanField()),
                ('tarjetas_debito', models.BooleanField()),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('Buffet', 'Buffet'), ('Comida rápida', 'Comida rápida'), ('Casual', 'Casual'), ('De autor', 'De autor'), ('Gourmet', 'Gourmet'), ('Temático', 'Temático')], default='Gourmet', max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='establecimientos/foto-principal')),
                ('imagen_banner', models.ImageField(upload_to='establecimientos/banner')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.IntegerField()),
                ('comensales', models.IntegerField()),
                ('creado', models.DateField(auto_now_add=True)),
                ('editado', models.DateField(auto_now=True)),
                ('fecha_reserva', models.DateField()),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.Establecimientos')),
            ],
        ),
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='users',
            name='nombreUsuario',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
