# Generated by Django 2.2.13 on 2022-05-21 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220508_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.IntegerField()),
                ('comensales', models.IntegerField()),
                ('creado', models.DateField(auto_now_add=True)),
                ('editado', models.DateField(auto_now=True)),
                ('fecha_reserva', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Comida',
        ),
        migrations.RemoveField(
            model_name='establecimientos',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='establecimientos',
            name='servicios',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Servicios',
        ),
        migrations.AddField(
            model_name='reserva',
            name='establecimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.Establecimientos'),
        ),
    ]
